#!/usr/bin/env bash
#
# sync-version.sh — Read version.txt and write app/Taskmato/Config/Version.xcconfig
#
# Converts the release-please version string into Xcode build settings:
#   MARKETING_VERSION      — the full semver string (e.g. 1.0.0-alpha.14)
#   CURRENT_PROJECT_VERSION — a monotonically increasing integer
#
# For pre-release versions (e.g. 1.0.0-alpha.14), CURRENT_PROJECT_VERSION is
# the pre-release number (14). For stable releases (e.g. 1.2.3),
# CURRENT_PROJECT_VERSION is derived from the semver components (major * 10000
# + minor * 100 + patch).
#
# Usage:
#   scripts/sync-version.sh [--version-file <path>] [--out <path>]
#
# Defaults:
#   --version-file  version.txt (relative to repo root)
#   --out           app/Taskmato/Config/Version.xcconfig

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

VERSION_FILE="$REPO_ROOT/version.txt"
OUT_FILE="$REPO_ROOT/app/Taskmato/Config/Version.xcconfig"

while [[ $# -gt 0 ]]; do
    case "$1" in
        --version-file) VERSION_FILE="$2"; shift 2 ;;
        --out)          OUT_FILE="$2";     shift 2 ;;
        *) echo "Unknown argument: $1" >&2; exit 1 ;;
    esac
done

if [[ ! -f "$VERSION_FILE" ]]; then
    echo "Error: version file not found: $VERSION_FILE" >&2
    exit 1
fi

VERSION_STRING="$(tr -d '[:space:]' < "$VERSION_FILE")"

if [[ -z "$VERSION_STRING" ]]; then
    echo "Error: version file is empty: $VERSION_FILE" >&2
    exit 1
fi

# Parse semver with optional pre-release label (e.g. 1.0.0-alpha.14)
if [[ "$VERSION_STRING" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)-[a-zA-Z]+\.([0-9]+)$ ]]; then
    # Pre-release: use the pre-release number as CURRENT_PROJECT_VERSION
    MAJOR="${BASH_REMATCH[1]}"
    MINOR="${BASH_REMATCH[2]}"
    PATCH="${BASH_REMATCH[3]}"
    PRE="${BASH_REMATCH[4]}"
    BUILD_NUMBER="$PRE"
elif [[ "$VERSION_STRING" =~ ^([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
    # Stable release: encode as major*10000 + minor*100 + patch
    MAJOR="${BASH_REMATCH[1]}"
    MINOR="${BASH_REMATCH[2]}"
    PATCH="${BASH_REMATCH[3]}"
    BUILD_NUMBER=$(( MAJOR * 10000 + MINOR * 100 + PATCH ))
else
    echo "Error: unrecognised version format: $VERSION_STRING" >&2
    exit 1
fi

MARKETING_VERSION="$VERSION_STRING"

mkdir -p "$(dirname "$OUT_FILE")"

cat > "$OUT_FILE" <<EOF
// Auto-generated by scripts/sync-version.sh — DO NOT EDIT
// Source: $VERSION_FILE
MARKETING_VERSION = $MARKETING_VERSION
CURRENT_PROJECT_VERSION = $BUILD_NUMBER
EOF

echo "sync-version: $MARKETING_VERSION (build $BUILD_NUMBER) → $OUT_FILE"
