name: 'Setup tools & code dependencies'
description: 'Check out code, set up Node.js and PNPM, and install dependencies'

inputs:
  node-version-file:
    description: 'Path to node version file'
    default: '.tool-versions'
    required: false

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Setup nodeJS
      uses: actions/setup-node@v4
      with:
        node-version-file: ${{ inputs.node-version-file }}
        cache: pnpm

    - name: Install dependencies
      run: pnpm install --frozen-lockfile
      shell: bash
