name: Build

on:
  workflow_call:
  pull_request:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6.0.2

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.3.app

      - name: Sync version
        run: bash scripts/sync-version.sh

      - name: Build
        run: |
          xcodebuild build \
            -project app/Taskmato.xcodeproj \
            -scheme Taskmato \
            -configuration Debug \
            -destination 'platform=macOS' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
