name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/code-build.yaml
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Tools & Dependencies
        uses: ./.github/actions/setup-code

      - name: Download build artifacts
        id: download
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: ${{ needs.build.outputs.artifact_path }}

      - name: Deploy to Netlify
        run: |
          pnpm exec netlify deploy \
            --dir ${{ steps.download.outputs.download-path }} \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            --prod
