name: Build and Deploy

env:
  ARTIFACT_NAME: build-artifacts
  ARTIFACT_PATH: dist

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/code-build.yaml
    secrets: inherit
    with:
      artifact_name: ${{ env.ARTIFACT_NAME }}
      artifact_path: ${{ env.ARTIFACT_PATH }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.ARTIFACT_PATH }}

      - name: Deploy to Netlify
        run: |
          pnpm exec netlify deploy \
            --dir ${{ env.ARTIFACT_PATH }} \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            --prod
