name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/code-build.yaml
    secrets: inherit

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.artifact_name }}
          path: dist # Path where the artifacts will be downloaded

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.10.0 # Keep this in sync with the version in .tool-versions
          run_install: false

      - name: Install Netlify
        run: pnpm add netlify-cli@21.3.0 -g

      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }} \
            --prod
