name: Report test coverage

on:
  workflow_run:
    workflows: [Test]
    types:
      - completed

jobs:
  report:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Setup tools & dependencies
        uses: ./.github/actions/setup-code

      - name: Download test coverage
        uses: actions/download-artifact@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Report test coverage on pull request
        uses: davelosert/vitest-coverage-report-action@v2
